# Generated by Django 6.0.2 on 2026-03-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_team_task_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
